### 1. Add queue
POST {{host}}/sqs/queue HTTP/1.1
content-type: application/json

{
    "queue":"local-queue"
}

### 2. List queue
GET {{host}}/sqs/queues?queue=local-queue HTTP/1.1
content-type: application/json

### 3. Get queue by QueueName
GET {{host}}/sqs/queue HTTP/1.1
content-type: application/json

### 4. Remove queue by url
DELETE {{host}}/sqs/queue HTTP/1.1
content-type: application/json

### 5. Disparar mensagem para uma fila
POST {{host}}/sqs/dispatch-message HTTP/1.1
content-type: application/json

### 6. Recebe uma ou mais mensagens da fila
GET {{host}}/sqs/receive-messages HTTP/1.1
content-type: application/json

### 7. Recebe e apaga uma ou mais mensagens da fila
GET {{host}}/sqs/receive-messages-and-delete HTTP/1.1
content-type: application/json
