### 1. Add topic
POST {{host}}/sns/topic HTTP/1.1
content-type: application/json

{
    "topic":"local-topic"
}

### 2. List topics
GET {{host}}/sns/topics HTTP/1.1
content-type: application/json

### 3. Get topic by name
GET {{host}}/sns/topic?topic=local-topic HTTP/1.1
content-type: application/json

### 4. Delete topic by name
DELETE {{host}}/sns/topic HTTP/1.1
content-type: application/json

{
    "topic":"local-topic"
}

